Repository PetCommunityWeb/PetCommunityFront, pull requests merged in 2023-09, with the labels that each got.

#36 [Refactor] 채팅방 수정
  src/views/ChatRoom.vue
  src/views/RealtimeConsult.vue
Labels: refactor

#37 [Refactor] 병원등록, 예약, 프로필 조회 리팩터링, 알림기능 추가
  src/components/AppHeader.vue
  src/components/NotificationIcon.vue
  src/mixins/hospitalMixin.js
  src/router/index.js
  src/views/HospitalDetail.vue
  src/views/HospitalManagement.vue
  src/views/MyPage.vue
Labels: enhancement

#41 [Feature] 예약가능 슬롯 자동 추가
  src/views/HospitalDetail.vue
  src/views/HospitalManagement.vue
Labels: enhancement

#44 [Refactor] notification, refreshToken 관련 리팩터링
  src/axios/axios-instance.js
  src/components/AppHeader.vue
  src/components/NotificationIcon.vue
  src/views/LoginView.vue
Labels: refactor

#46 feat: 채팅방 삭제
  src/views/RealtimeConsult.vue
Labels: enhancement

#48 [Feature] alert 통일화 / console 에러 제거
  src/axios/axios-instance.js
  src/components/FeedBoard.vue
  src/mixins/hospitalMixin.js
  src/views/HospitalDetail.vue
  src/views/LoginView.vue
  src/views/MyPage.vue
  src/views/RealtimeConsult.vue
Labels: refactor

#53 [Feature] 카테고리별 병원 조회
  src/views/FindHospital.vue
Labels: enhancement

#55 [Feature] feed 좋아요 순 조회 추가
  src/components/FeedBoard.vue
  src/methods/FeedBoard.js
  src/styles/FeedBoardStyle.css
Labels: enhancement

#57 [Refactor] 채팅방 1대1로 변경
  src/views/ChatRoom.vue
  src/views/RealtimeConsult.vue
Labels: enhancement, refactor

#61 [Feature] feed 댓글 순 조회 추가
  src/components/FeedBoard.vue
  src/components/NotificationIcon.vue
  src/methods/FeedBoard.js
  src/styles/FeedBoardStyle.css
Labels: enhancement

#62 [Refactor] console 로그 확인
  src/views/OAuth2.vue
Labels: enhancement

#66 [Refactor] websocket 연결 원본 ec2로 설정
  src/views/ChatRoom.vue
Labels: refactor

#70 [Feature] 팁 검색어 추가 및 썸네일 업로드
  src/components/TipBoard.vue
  src/components/TipDetail.vue
Labels: enhancement

#72 [Feature] 팁 다중 파일 첨부
  image/ServiceArchitecture_v2.png
  public/index.html
  src/components/TipBoard.vue
  src/components/TipCreate.vue
  src/components/TipDetail.vue
Labels: enhancement

#73 [Fix] 검색 시에도 썸네일 나타나도록 수정
  src/components/TipBoard.vue
Labels: enhancement
